Updateed readme
finos/common-cloud-controls pull request #196
Opened 2024-06-12 11:28 UTC by robmoffat

2024-06-12 11:29 UTC, robmoffat commented
@Alexstpierrework

2024-06-12 12:01 UTC, sshiells-scottlogic requested changes
Appreciate this ask isn't part of your changes but feels like a good time to fix

2024-06-12 12:01 UTC, sshiells-scottlogic commented on Readme.md
> +### FINOS CCC Steering Committeee Members
Can we remove the extra e from the end of committee?

2024-06-12 12:17 UTC, sshiells-scottlogic approved these changes
Thanks for the update. Looks good to me.

2024-06-12 14:02 UTC, sshiells-scottlogic commented on docs/governance/finos-poc.md
> +# FINOS Point-of-Contact (POC)
In some places we link to the FINOS POC section here: https://github.com/finos/common-cloud-controls/blob/main/docs/governance/steering/charter.md#finos-point-of-contact

Should these links be updated to point to this page?

2024-06-12 15:41 UTC, sshiells-scottlogic commented on docs/governance/finos-poc.md
> +# FINOS Point-of-Contact (POC)
Added

2024-06-12 15:45 UTC, eddie-knight commented
Very confused to see duplication reduction listed as an owner 🤔 Doesn't match what I see in the CODEOWNERS file.

2024-06-12 16:31 UTC, eddie-knight commented on Readme.md
> +| FINOS CCC Maintainer | Representing   | Seat      |
```suggestion
| Name                 | Representing   | Seat      |
```

Feels like "maintainer" is opening more questions than it answers here

2024-06-12 17:34 UTC, jared-lambert approved these changes
Nice updates.

2024-06-12 19:01 UTC, TheJuanAndOnly99 commented
/easycla

2024-06-13 10:55 UTC, robmoffat commented on Readme.md
> +> CCC aims to standardize cloud security controls for the banking sector, providing a common set of controls that CSPs can implement to meet the requirements of FS firms. As multiple FS firms are inv
this style came from https://github.com/finos/morphir?tab=readme-ov-file#what-are-the-benefits originally, but I agree, it's an abuse of markdown and we can get rid of it

2024-06-13 10:56 UTC, robmoffat commented on Readme.md
> +Please visit [participants.md](participants.md) and raise a Pull Request by adding your `name`, `organisation` and `enrollment date` to the markdown file.
Yeah, I've seen this before!   

Members should really refer to FINOS members (i.e. Gold, Silver, Platinum etc) whereas participants are people who are engaged in the project/meetings/github etc.

2024-06-13 10:58 UTC, robmoffat commented on Readme.md
> +### FINOS CCC Steering Committee Members
```suggestion
### FINOS CCC Steering Committee
```

2024-06-13 10:59 UTC, robmoffat commented on Readme.md
> +Please visit [participants.md](participants.md) and raise a Pull Request by adding your `name`, `organisation` and `enrollment date` to the markdown file.
Have removed the usage of the word "member" from the README at least.

2024-06-13 14:04 UTC, molssongroup commented
/easycla

2024-06-13 15:34 UTC, jared-lambert commented
/easycla

2024-06-13 15:57 UTC, robmoffat commented
Well done @jared-lambert on getting through the CCLA process!

2024-06-13 21:46 UTC, eddie-knight commented on Readme.md
> +FINOS Common Cloud Controls (FINOS CCC) is the codename for an open standard project, originally proposed by Citi and currently incubating in FINOS, to describe consistent controls for compliant publ
```suggestion
FINOS Common Cloud Controls (FINOS CCC) is an open standard project that describes consistent controls for compliant public cloud deployments in the financial services (FS) sector.
```

2024-06-20 16:21 UTC, robmoffat commented
> Waiting on code owner review from finos/ccc-steerco

who is this?

2024-06-20 16:31 UTC, eddie-knight approved these changes
LGTM! Thanks @robmoffat!

2024-06-20 16:32 UTC, merged