Creation of Global Markdown Formatting and Linting Standards
finos/common-cloud-controls pull request #243
Opened 2024-07-08 02:53 UTC by damienjburks

## Summary

This is the initial PR for creating the global markdown formatting and lining standards for the entire project. There is a new folder within the governance section of our project that will also house the release strategy and WG formatting standards (very soon). 

The information listed here correlates with what has already been done with the GitHub Action PR: #223 

Let me know if you have any questions, comments, or concerns.

## Linked Issues/PRs

- #209 
- #223

2024-07-09 10:20 UTC, sshiells-scottlogic reviewed
Looks good. I left a question about where this should belong, and also a couple of minor comments.

2024-07-09 10:20 UTC, sshiells-scottlogic commented on docs/governance/content-standards-and-practices/README.md
> +This directory will contain the conten development standards and practices, where you can find all the necessary guidelines and standards for formatting, linting, and releasing content within our pro
Change "conten" to "content"

2024-07-09 10:20 UTC, sshiells-scottlogic commented on docs/governance/content-standards-and-practices/README.md
Should this be a "policy" contained in "community-policies"?

We currently have "comminity-guidelines" which are strong suggestions on what WGs should do, and "community-policies" which are things WGs must adhere to?

The wording here suggests that this should be a policy to me? If you agree, then maybe we need to change the use of "guidelines" in this text?

2024-07-09 10:20 UTC, sshiells-scottlogic commented on docs/governance/content-standards-and-practices/README.md
> +3. **Check Compliance Regularly:** Regularly review your work against these standards to ensure ongoing compliance, especially before merges and releases. We have automated processes in place that wi
Should we use "markdown" instead of "MD" for clarity?

2024-07-10 15:21 UTC, damienjburks commented on docs/governance/content-standards-and-practices/README.md
I think that's a great idea. I just updated the wording a bit and moved everything into the community-policies directory. 😄

2024-07-10 15:22 UTC, damienjburks commented
@sshiells-scottlogic addressed all of your comments, let me know if there is anything else you think I need to address.

2024-07-10 15:29 UTC, sshiells-scottlogic approved these changes

2024-07-10 21:27 UTC, damienjburks commented
@eddie-knight please review and let me know your thoughts on this.

2024-07-10 21:33 UTC, eddie-knight commented
Hey @damienjburks — the only hangup here is that we already wrote "policies may be created or modified by a vote of the SC."

If you want to merge this in as a policy, it'll need to wait in PR mode until we get 4 votes from steerco members. We can send out an email requesting folks come take a stance, or we can merge this as a guideline and then call for it to be promoted on the next SC call. I prefer the second option, if that's okay with you.

2024-07-10 21:33 UTC, eddie-knight requested changes
Hey @damienjburks — the only hangup here is that we already wrote "policies may be created or modified by a vote of the SC."

If you want to merge this in as a policy, it'll need to wait in PR mode until we get 4 votes from steerco members. We can send out an email requesting folks come take a stance, or we can merge this as a guideline and then call for it to be promoted on the next SC call. 

I prefer the second option, if that's okay with you. The only change would be to move this into the other directory.

2024-07-10 21:34 UTC, damienjburks commented
@eddie-knight that is fine with me. Shall I revert the wording to guidelines then?

2024-07-10 21:36 UTC, eddie-knight commented
Yep, good shout.

2024-07-10 21:50 UTC, damienjburks commented
@eddie-knight everything has been updated. let me know if this works for you.

2024-07-10 21:53 UTC, eddie-knight commented on markdown/formatting-guidelines.md
Looks like this is unintentional

2024-07-10 21:55 UTC, damienjburks commented on markdown/formatting-guidelines.md
Fixed!

2024-07-10 21:56 UTC, eddie-knight approved these changes

2024-07-10 21:57 UTC, merged