Add in new object storage controls on encryption for impact and replication to untrusted destinations
finos/common-cloud-controls pull request #305
Opened 2024-08-08 11:10 UTC by mlysaght2017

Need to work on tests, but would like to get to initial feedback on control objectives first

2024-08-09 18:58 UTC, mlysaght2017 commented on services/storage/object/controls.md
> +## CCC.OS.C9: Prevent Replication to Untrusted Destinations
Thinking here is that untrusted destinations (resources) are any that exist outside of a defined identity/network perimeter (e.g.) at the organization level. E.g. if targeted destination/resource is not within a member project/account/subscription within the org, then deny.

2024-08-12 13:56 UTC, nas-hub commented on services/storage/object/controls.md
> +## CCC.OS.C9: Prevent Replication to Untrusted Destinations
Got it, we may need to have a glossary of terms we use in CCC and define its scope.  Or probably just qualify the untrusted destination further contracting it with Trusted Identity Perimeter, Truster Network Perimeter similar to the term Trusted Computing Base defined in NIST/ISC2. 

The control and testing requirement LGTM

2024-08-15 16:21 UTC, eddie-knight requested changes
[will add note later]

2024-08-28 09:30 UTC, mlysaght2017 commented
@damienjburks @eddie-knight can you please review/approve if you haven't already - I've just added in an extra line of detail on what we mean by untrusted resource/untrusted perimeters based on feedback from @nas-hub

2024-08-29 01:11 UTC, damienjburks approved these changes
LGTM! 🚀

2024-08-29 01:19 UTC, eddie-knight approved these changes

2024-08-29 01:19 UTC, merged